packages:
  - apps/*
  - internal-packages/*
  - packages/*
  - tools/*
catalog:
  "@biomejs/biome": 1.9.4
  typescript: 5.7.3
  zod: 3.24.1
  nanoid: 5.0.9
  tsup: 8.3.5
  "@turbo/gen": 2.3.3
  next: 15.1.6
  unstorage: 1.14.4
  ai: 4.1.28
  "@types/node": 22.10.7
  "@types/react": 19.0.4
  "@types/react-dom": 19.0.2
  postcss: 8.5.1
  tailwindcss: 4.0.3
  "@tailwindcss/postcss": 4.0.3
  react: 19.0.0
  react-dom: 19.0.0
  node-loader: 2.1.0
  vitest: 3.0.5
  "@radix-ui/react-tabs": 1.1.2
  lucide-react: 0.473.0
  clsx: 2.1.1
  "@xyflow/react": 12.4.1
  openai: 5.0.0-alpha.0
  "@ai-sdk/openai": 1.1.9
  "@ai-sdk/anthropic": 1.1.6
  "@ai-sdk/google": 1.1.11
  "@tailwindcss/typography": 0.5.16
  tailwindcss-animate: 1.0.7
  react-resizable-panels: 2.1.7
  radix-ui: 1.1.2
  motion: 12.3.1
  "@tiptap/pm": 2.11.5
  "@tiptap/core": 2.11.5
  "@tiptap/react": 2.11.5
  "@tiptap/extension-document": 2.11.5
  "@tiptap/extension-paragraph": 2.11.5
  "@tiptap/extension-text": 2.11.5
  "@tiptap/extension-bold": 2.11.5
  "@tiptap/extension-list-item": 2.11.5
  "@tiptap/extension-bullet-list": 2.11.5
  "@tiptap/extension-code": 2.11.5
  "@tiptap/extension-code-block-lowlight": 2.11.5
  "@tiptap/extension-italic": 2.11.5
  "@tiptap/extension-ordered-list": 2.11.5
  "@tiptap/extension-strike": 2.11.5
  "@tiptap/html": 2.11.5
  highlight.js: 11.11.1
  lowlight: 3.3.0
  turndown: 7.2.0
  "@types/turndown": 5.0.5
  pluralize: 8.0.0
  "@types/pluralize": 0.0.33
  react-markdown: 9.0.3
  marked: 15.0.7
