name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      PLAYWRIGHT_BASE_URL:
        description: 'Base URL for Playwright'
        required: false

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: Set node version to 24.x
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x
          cache: 'pnpm'
      - run: pnpm install
      - name: Store Playwright's Version
        shell: bash
        run: |
          PLAYWRIGHT_VERSION=$(pnpm -s dlx playwright --version | sed 's/Version //')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers & OS deps
        shell: bash
        run: pnpm --filter studio.giselles.ai exec playwright install --with-deps
      - name: Run e2e tests
        run: pnpm test:e2e
        working-directory: apps/studio.giselles.ai
        env:
          PLAYWRIGHT_BASE_URL: ${{ github.event.inputs.PLAYWRIGHT_BASE_URL != '' && github.event.inputs.PLAYWRIGHT_BASE_URL || secrets.PLAYWRIGHT_BASE_URL }}
          PLAYWRIGHT_LOGIN_EMAIL: ${{ secrets.PLAYWRIGHT_LOGIN_EMAIL }}
          PLAYWRIGHT_LOGIN_PASSWORD: ${{ secrets.PLAYWRIGHT_LOGIN_PASSWORD }}
